package com.cmnit.gatherdata.modules.bean

case class GantryVehDisData(
                             picId: String,
                             gantryId: String,
                             gantryHex: String,
                             picTime: String,
                             gantryOrderNum: String,
                             driveDir: String,
                             cameraNum: String,
                             hourBatchNo: String,
                             shootPosition: String,
                             laneNum: String,
                             vehiclePlate: String,
                             vehicleSpeed: String,
                             identifyType: String,
                             vehicleModel: String,
                             vehicleColor: String,
                             imageSize: String,
                             licenseImageSize: String,
                             binImageSize: String,
                             reliability: String,
                             vehFeatureCode: String,
                             faceFeatureCode: String,
                             verifyCode: String,
                             tradeId: String,
                             matchStatus: String,
                             validStatus: String,
                             dealStatus: String,
                             relatedPicId: String,
                             allRelatedPicId: String,
                             stationDBTime: String,
                             stationDealTime: String,
                             stationValidTime: String,
                             stationMatchTime: String,
                             receiveTime: String,
                             var year: String,
                             var month: String,
                             var day: String,
                             var hour: String
                           ) {}
