package com.cmnit.gatherdata.modules.bean

case class TollChargerShiftExSumInfo(
                                      auth: String,
                                      batchNum: String,
                                      station: String,
                                      lane: String,
                                      stationId: String,
                                      laneId: String,
                                      workDate: String,
                                      shift: String,
                                      tollCollectorID: String,
                                      tollCollectorName: String,
                                      laneType: String,
                                      bL_SubCenter: String,
                                      bL_Center: String,
                                      startTime: String,
                                      endTime: String,
                                      statusFlag: String,
                                      invStartNo: String,
                                      invNum: String,
                                      badInvNum: String,
                                      cashRecordCnt: String,
                                      vCnt: String,
                                      inductCnt: String,
                                      CPCCnt: String,
                                      papCnt: String,
                                      damCardCnt: String,
                                      etcCardCnt: String,
                                      cashFee: String,
                                      thirdPayFee: String,
                                      unipayFee: String,
                                      etcFee: String,
                                      alipayFee: String,
                                      weChatFee: String,
                                      cashCardFee: String,
                                      thirdCardFee: String,
                                      unipayCardFee: String,
                                      etcCardFee: String,
                                      alipayCardFee: String,
                                      weChatCardFee: String,
                                      unpayCardCost: String,
                                      cashFreeMoney: String,
                                      cashRebateMoney: String,
                                      posFreeMoney: String,
                                      posRebateMoney: String,
                                      transCnt: String,
                                      transFeeSum: String,
                                      ticketFee: String,
                                      unifiedFee: String,
                                      invEndNo: String,
                                      receivetime: String,
                                      branchAgency: String,
                                      var year: String,
                                      var month: String,
                                      var day: String
                                    ) {}
