package com.cmnit.gatherdata.modules.bean

case class TollHeartBeatInfo(
                              auth: String,
                              id: String,
                              tollStationId: String,
                              tollLaneId: String,
                              tollStation: String,
                              tollLane: String,
                              laneType: String,
                              laneSign: String,
                              heartBeatTime: String,
                              vehicleGreyListVersion: String,
                              vehicleGreyListRecTime: String,
                              vehicleBlackListVersion: String,
                              vehicleBlackListRecTime: String,
                              obuBlackListVersion: String,
                              obuBlackListRecTime: String,
                              cpuBlackListVersion: String,
                              cpuBlackListRecTime: String,
                              cpcGreyListVersion: String,
                              cpcGreyListRecTime: String,
                              spcRateVersion: String,
                              notenableSpcRateVersion: String,
                              notenableSpcRateRecTime: String,
                              laneStatus: String,
                              rsuStatus: String,
                              laneControllerStatus: String,
                              serverStatus: String,
                              cardReaderStatus: String,
                              railerStatus: String,
                              payEquipmentStatus: String,
                              VPLRStatus: String,
                              vehDetectorStatus: String,
                              axleDetectorStatus: String,
                              lightDetectorStatus: String,
                              HDVideoStatus: String,
                              feeBoardStatus: String,
                              hintsBoardStatus: String,
                              tradfficLight1Status: String,
                              infoBoardStatus: String,
                              entryOverloadStatus: String,
                              laneControllerManuID: String,
                              sysVer: String,
                              opsCode: String,
                              opsVer: String,
                              RSUManuID: String,
                              RSUHardwareVersion: String,
                              RSUSoftwareVersion: String,
                              cardReaderManuID: String,
                              cardReaderVersion: String,
                              chargeMode: String,
                              VPLRManuID: String,
                              receivetime: String,
                              blackIncrVer: String,
                              branchAgency: String,
                              var year: String,
                              var month: String,
                              var day: String,
                              var hour: String
                            ) {}
