package com.cmnit.gatherdata.modules.bean

case class TollEnBillInfo(
                           auth: String,
                           id: String,
                           transCode: String,
                           bl_SubCenter: String,
                           bl_Center: String,
                           lDate: String,
                           shift: String,
                           batchNum: String,
                           loginTime: String,
                           triggerTime: String,
                           operId: String,
                           operName: String,
                           monitor: String,
                           monitorName: String,
                           monitorTime: String,
                           laneAppVer: String,
                           laneType: String,
                           enTollStation: String,
                           enTollLane: String,
                           enTollStationHex: String,
                           enTollLaneHex: String,
                           enTollStationId: String,
                           enTollLaneId: String,
                           enTime: String,
                           mediaType: String,
                           obuSign: String,
                           obuIssueFlag: String,
                           obuId: String,
                           supplierId: String,
                           vCount: String,
                           balanceBefore: String,
                           transFee: String,
                           cardType: String,
                           cardNet: String,
                           cardId: String,
                           cardBox: String,
                           cardCount: String,
                           cardSn: String,
                           cardCnt: String,
                           inductCnt: String,
                           vlp: String,
                           vlpc: String,
                           identifyVlp: String,
                           identifyVlpc: String,
                           vehicleType: String,
                           vehicleClass: String,
                           TAC: String,
                           transType: String,
                           terminalNo: String,
                           enWeight: String,
                           axisInfo: String,
                           limitWeight: String,
                           overWeightRate: String,
                           enAxleCount: String,
                           electricalPercentage: String,
                           terminalTransNo: String,
                           signStatus: String,
                           description: String,
                           paraVer: String,
                           cardVersion: String,
                           OBUVersion: String,
                           keyNum: String,
                           keyPressInfo: String,
                           specialType: String,
                           laneSpInfo: String,
                           spInfo: String,
                           vehicleSignId: String,
                           passId: String,
                           vehicleSign: String,
                           vehicleId: String,
                           identifyVehicleId: String,
                           direction: String,
                           operationMedia: String,
                           chargeMode: String,
                           receivetime: String,
                           identifyVehicleType: String,
                           obuUserType: String,
                           obuTotalWeight: String,
                           obuMaintenanceWeight: String,
                           obuPermittedTowWeight: String,
                           obuPermittedWeight: String,
                           obuLength: String,
                           obuWeight: String,
                           obuHeight: String,
                           certNo: String,
                           branchAgency: String,
                           //                           equipCode: String,
                           //                           speed: String,
                           //                           Length: String,
                           //                           Width: String,
                           //                           height: String,
                           //                           isBlackvehicle: String,
                           var year: String,
                           var month: String,
                           var day: String,
                           var hour: String
                         ) {}
