package com.cmnit.gatherdata.modules.bean

case class TollOpLogInfo(
                          auth: String,
                          opID: String,
                          opType: String,
                          operTime: String,
                          station: String,
                          lane: String,
                          wasteSN: String,
                          oper: String,
                          operName: String,
                          superOper: String,
                          superOperName: String,
                          monTime: String,
                          lDate: String,
                          shift: String,
                          laneStatus: String,
                          loginTime: String,
                          triggerTime: String,
                          PSAMTerm: String,
                          laneType: String,
                          cardType: String,
                          card: String,
                          cardNet: String,
                          OBUProvider: String,
                          OBU: String,
                          spInfo: String,
                          devStatus: String,
                          vCnt: String,
                          inductCnt: String,
                          laneAppVer: String,
                          verifyCode: String,
                          receivetime: String,
                          branchAgency: String,
                          var year: String,
                          var month: String,
                          var day: String,
                          var hour: String
                        ) {}
