package com.cmnit.gatherdata.modules.bean

case class TollRealTimeMonitorInfo(
                                    auth: String,
                                    id: String,
                                    tollStationId: String,
                                    tollLaneId: String,
                                    laneSign: String,
                                    tollStation: String,
                                    tollLane: String,
                                    laneFLag: String,
                                    monitorTime: String,
                                    intoTime: String,
                                    miliSecond: String,
                                    passSign: String,
                                    logicalFileCause: String,
                                    bnErrCause: String,
                                    OBUSN: String,
                                    OBUMAC: String,
                                    OBUVersion: String,
                                    OBUState: String,
                                    Vlp: String,
                                    Vlpc: String,
                                    OBUVehicleType: String,
                                    CPUVersion: String,
                                    CPUIssuer: String,
                                    CPUCardSnNo: String,
                                    enVehicleType: String,
                                    enPassStatus: String,
                                    EnVlp: String,
                                    EnVlpc: String,
                                    identifyVlp: String,
                                    identifyVlpc: String,
                                    outofTime: String,
                                    vehSpeed: String,
                                    chargeMode: String,
                                    OBUVehicleId: String,
                                    enVehicleId: String,
                                    identifyVehicleId: String,
                                    receivetime: String,
                                    branchAgency: String,
                                    var year: String,
                                    var month: String,
                                    var day: String,
                                    var hour: String
                                  ) {}
